volumes:
  data: { driver: local }

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - data:/data

  serve:
    build: ./
    command: [ "deno", "task", "serve" ] 
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - 8080:8080
    restart: unless-stopped

  update:
    build: ./
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
