volumes:
  data: { driver: local }

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - data:/data

  serve:
    build: ./
    command: [ "deno", "task", "serve" ] 
    env_file: .env
    restart: unless-stopped

  update:
    build: ./
    env_file: .env
    restart: unless-stopped
