volumes:
  data: { driver: local }

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - data:/data

  serve:
    build: ./
    command: [ "deno", "task", "serve" ] 
    depends_on:
      - redis
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8080:8080
    restart: unless-stopped

  update:
    build: ./
    depends_on:
      - redis
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
